Previous in attempt 1 and 2, I normalized all the features and did not pay attention to categorical vs continuous data. The best results were achieved by XGboosting. I had tried other methods like logisticregression which failed terribly. I also noticed the imbalanced nature of the data and decided to use balanced bagging with decisiontreeclassifier, which worked great, and also randomforestsclassifier, which worked even better. Now I want to understand the data and do some intelligent preprocessing. Aim is to check performance of XGboost after better preprocessing.

However, lets first test our best xgboost without normalizing any feature.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from datetime import datetime
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBClassifier

In [2]:
def average(df):
    sum = 0
    count = 0
    for x in df['f1']:
        if x!=-1:
            sum+=x
            count+=1
    avg = sum/count
    return avg

In [3]:
#Timer function
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [4]:
df = pd.read_csv("train_final.csv")
df.describe()
f1_avg = average(df)
df['f1'].replace(-1,f1_avg, inplace = True)
df.describe()

,Id,Y,f1,f2,f3,f4,f5,f6,f7,f8,...,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24
count,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,...,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,16383.000000,1.638300e+04,16383.000000
mean,8192.000000,0.942135,43031.415720,1.044375,11.770938,118323.581456,1.044436,0.050052,117089.674113,169730.178600,...,25894.316914,119045.099005,184622.040835,1.047305,125959.667765,1.044558,1.045718,1.041934,3.271890e+04,1.043948
std,4729.509065,0.233495,33596.053696,0.264806,353.187115,4518.059755,0.265601,0.293892,10261.292970,69396.677853,...,36086.993946,18321.987129,100590.811845,0.306239,31091.344158,0.262576,0.266874,0.246597,3.184929e+06,0.259640
min,1.000000,0.000000,37.000000,1.000000,1.770000,23779.000000,1.000000,0.000000,4292.000000,4673.000000,...,25.000000,4674.000000,3130.000000,1.000000,117879.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000
25%,4096.500000,1.000000,20331.000000,1.000000,1.770000,118096.000000,1.000000,0.000000,117961.000000,117906.000000,...,4554.000000,118395.000000,118398.000000,1.000000,118274.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000
50%,8192.000000,1.000000,35530.000000,1.000000,1.770000,118300.000000,1.000000,0.000000,117961.000000,128130.000000,...,13234.000000,118929.000000,119095.000000,1.000000,118568.000000,1.000000,1.000000,1.000000,2.000000e+00,1.000000
75%,12287.500000,1.000000,74240.500000,1.000000,3.540000,118386.000000,1.000000,0.000000,117961.000000,234498.500000,...,38902.000000,120539.000000,290919.000000,1.000000,120006.000000,1.000000,1.000000,1.000000,9.000000e+00,1.000000
max,16383.000000,1.000000,312152.000000,7.000000,43910.160000,286791.000000,9.000000,10.000000,311178.000000,311867.000000,...,311696.000000,286792.000000,308574.000000,18.000000,311867.000000,8.000000,8.000000,7.000000,4.042886e+08,8.000000

In [21]:
y = df.loc[:,'Y']
X = df.loc[:,'f1':'f24']
X_train, X_valid, y_train, y_valid = train_test_split(X,y,train_size = 0.75, test_size = 0.25,random_state = 42, shuffle = True)

In [26]:
model_xgb = XGBClassifier(n_estimators=800, max_depth=4, learning_rate=0.05, n_jobs=-1, random_state=42) 
model_xgb.fit(X_train, y_train)
soft_probs = model_xgb.predict_proba(X_valid)
valid_auc = roc_auc_score(y_valid, soft_probs[:,1])
print(valid_auc)
train_preds = model_xgb.predict(X_train)
acc = accuracy_score(y_train, train_preds)
print(acc)
preds = model_xgb.predict(X_valid)
acc = accuracy_score(y_valid, preds)
print(acc)

0.8648734965318772
0.9721657035891593
0.961181640625

Notice that without normalizing any data, it still gives similar results to xgboosting normalized data. I'll have another file called tuning.ipynb that grid searches on data that isnt normalized. Here, I will do some feature engineering and tune after.

From kaggle data histograms,
categorical features are: f2, f3, f5, f6, f9, f11, (f17?), f18, f19, f20, f21, f22, f24
Lets NOT normalize those columns. 
So only normalize f1, f4, f7, f8, f10, f12-f16,f24

In [39]:
# TODO: choose categorical data and normalize continuous features only.
f1 = X_train['f1']
f4 =  X_train['f4']
f7 = X_train['f7']
f8 =  X_train['f8']
f10 =  X_train['f10']
f1216 =  X_train.loc[:,'f12':'f16']
f24 =  X_valid['f24']
f1v = X_valid['f1']
f4v=  X_valid['f4']
f7v = X_valid['f7']
f8v =  X_valid['f8']
f10v =  X_valid['f10']
f1216v =  X_valid.loc[:,'f12':'f16']
f24v =  X_valid['f24']
feature_norm_train = pd.concat((f1,f4,f7,f8,f10,f1216,f24),axis=1, sort=False)
feature_norm_test = pd.concat((f1v,f4v,f7v,f8v,f10v,f1216v,f24v),axis=1, sort=False)
scaler = StandardScaler()
feature_norm_train = scaler.fit_transform(feature_norm_train)
feature_norm_test = scaler.transform(feature_norm_test)

# X_train = pd.concat((feature_norm_train['f1'],X_train.loc[:,'f2':'f3'],
#                     feature_norm_train['f4'],X_train.loc[:,'f5':'f6'],
#                    feature_norm_train['f7'],feature_norm_train['f8'],
#                      X_train.loc['f9'],feature_norm_train['f10'],
#                     X_train.loc['f11'],feature_norm_train.loc[:,'f12':'f16'],
#                     X_train.loc[:,'f17':'f23'],feature_norm_train['f24']),axis=1,sort=False)

,f1,f4,f7,f8,f10,f12,f13,f14,f15,f16,f24
9858,35525.0,117944,117943,180251,6,1,118276,0.294049,46459,117945,1
2932,41648.0,118052,117961,117906,0,1,118322,1.879190,54618,118992,1
12843,80004.0,117962,117961,240983,1,1,117908,4.620103,1140,118352,1
5156,117804.0,117891,117890,117879,40,1,117880,1.000000,20434,117878,1
2677,81253.0,118343,117961,311622,0,1,118332,1.255183,6235,118437,1